"use client";

import type { Metadata } from "next";
import { MantineProvider, AppShell, Burger, AppShellNavbarConfiguration } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { Navbar } from "../Navbar";

import "@mantine/core/styles.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [opened, { toggle, close }] = useDisclosure(false);

    const navBreakpoint: AppShellNavbarConfiguration["breakpoint"] = "sm";

    return (
        <MantineProvider>
            <AppShell
                navbar={{ width: 300, breakpoint: navBreakpoint, collapsed: { mobile: !opened } }}
                padding="md"
            >
                <AppShell.Navbar>
                    <Burger opened={opened} onClick={toggle} hiddenFrom={navBreakpoint} size="md" p="lg" pt="xl" />
                    <Navbar close={close} />
                </AppShell.Navbar>
                <AppShell.Main>
                    <Burger opened={opened} onClick={toggle} hiddenFrom={navBreakpoint} size="md" mb="lg" />
                    {children}
                </AppShell.Main>
            </AppShell>
        </MantineProvider>
    );
}